// AUTO-GENERATED by sync-learning-content.ts — do not edit
import type { ContentManifest } from "@/lib/types";

export const manifest: ContentManifest = {
  podCount: 268,
  lessonCount: 3,
  moduleCount: 32,
  domains: ["AI Engineering","AI for Everyone","Business","DevOps","Financial Models","ML Models","Product & Engineering","Quant & Trading","Tools & Platforms"],
  lastSynced: "2026-04-06T02:04:12.821Z",
};
