// AUTO-GENERATED by sync-learning-content.ts — do not edit
import type { ContentManifest } from "@/lib/types";

export const manifest: ContentManifest = {
  podCount: 66,
  lessonCount: 3,
  moduleCount: 8,
  domains: ["AI Engineering", "Quant & Trading", "Financial Models", "Tools & Platforms", "ML Models", "General"],
  lastSynced: "2026-04-03T15:52:18.359Z",
};
