// AUTO-GENERATED by generate-quiz-questions.ts — do not edit
import type { Question } from "@/lib/types";

export const quizzes: Record<string, Question[]> = {
  "ai-batch-api": [
    {
      "id": "ai-batch-api-what",
      "question": "What best describes Claude Batch API?",
      "choices": [
        "A client-side JavaScript library for DOM rendering",
        "Anthropic's Message Batches API lets you send up to 100,000 requests in a single batch and get results asynchronously within 24 hours — at 50% off standard per-token pricing",
        "A CI/CD pipeline orchestrator for container deployments",
        "A database migration tool for PostgreSQL schemas"
      ],
      "correctIndex": 1,
      "explanation": "Anthropic's Message Batches API lets you send up to 100,000 requests in a single batch and get results asynchronously within 24 hours — at 50% off standard per-token pricing"
    },
    {
      "id": "ai-batch-api-fact-0",
      "question": "Which of these is true about Claude Batch API (Key Mechanics)?",
      "choices": [
        "Bulk classification — labeling datasets, tagging content, categorizing feedback",
        "Evaluation — running evals across hundreds of test cases",
        "Pricing: 50% discount on both input and output tokens",
        "Bulk generation — generating descriptions, summaries, or embeddings at scale"
      ],
      "correctIndex": 2,
      "explanation": "Pricing: 50% discount on both input and output tokens"
    },
    {
      "id": "ai-batch-api-section",
      "question": "\"POST /v1/messages/batches\" — which section of Claude Batch API does this belong to?",
      "choices": [
        "When to Use It",
        "Key Mechanics",
        "Cost Impact",
        "When NOT to Use It"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "ai-batch-api-bold-1",
      "question": "In the context of Claude Batch API, which term matches: \"Pricing: 50% discount on both input and output tokens\"?",
      "choices": [
        "SLA",
        "Pricing",
        "Limits",
        "50% off"
      ],
      "correctIndex": 1,
      "explanation": "Pricing — from the \"Key Mechanics\" section."
    }
  ],
  "ai-model-right-sizing": [
    {
      "id": "ai-model-right-sizing-what",
      "question": "What best describes Model Right-Sizing?",
      "choices": [
        "A database migration tool for PostgreSQL schemas",
        "Choosing the cheapest model that meets the quality bar for each task",
        "A CI/CD pipeline orchestrator for container deployments",
        "A client-side JavaScript library for DOM rendering"
      ],
      "correctIndex": 1,
      "explanation": "Choosing the cheapest model that meets the quality bar for each task"
    },
    {
      "id": "ai-model-right-sizing-bold-0",
      "question": "In the context of Model Right-Sizing, which term matches: \"Defaulting to Opus for everything — the #1 cost killer. Most tasks are Sonnet-tier.\"?",
      "choices": [
        "Using Sonnet for classification",
        "Defaulting to Opus for everything",
        "Ignoring output tokens",
        "Not testing downgrade quality"
      ],
      "correctIndex": 1,
      "explanation": "Defaulting to Opus for everything — from the \"Common Mistakes\" section."
    },
    {
      "id": "ai-model-right-sizing-fact-0",
      "question": "Which of these is true about Model Right-Sizing (Common Mistakes)?",
      "choices": [
        "A client-side JavaScript library for DOM rendering",
        "A CI/CD pipeline orchestrator for container deployments",
        "A database migration tool for PostgreSQL schemas",
        "Defaulting to Opus for everything — the #1 cost killer. Most tasks are Sonnet-tier."
      ],
      "correctIndex": 3,
      "explanation": "Defaulting to Opus for everything — the #1 cost killer. Most tasks are Sonnet-tier."
    },
    {
      "id": "ai-model-right-sizing-section",
      "question": "\"Model          Input/1M    Output/1M    Context    Best For\" — which section of Model Right-Sizing does this belong to?",
      "choices": [
        "The Decision Framework",
        "Task-to-Model Mapping",
        "Common Mistakes",
        "Key Mechanics — Claude Model Tiers (2026 Pricing)"
      ],
      "correctIndex": 3,
      "explanation": "This is from the \"Key Mechanics — Claude Model Tiers (2026 Pricing)\" section."
    },
    {
      "id": "ai-model-right-sizing-bold-1",
      "question": "In the context of Model Right-Sizing, which term matches: \"Using Sonnet for classification — Haiku handles simple labels at 3.75x less cost.\"?",
      "choices": [
        "Ignoring output tokens",
        "Using Sonnet for classification",
        "Not testing downgrade quality",
        "Defaulting to Opus for everything"
      ],
      "correctIndex": 1,
      "explanation": "Using Sonnet for classification — from the \"Common Mistakes\" section."
    }
  ],
  "ai-prompt-caching": [
    {
      "id": "ai-prompt-caching-what",
      "question": "What best describes Claude Prompt Caching?",
      "choices": [
        "A database migration tool for PostgreSQL schemas",
        "Prompt caching lets you mark parts of your prompt as cacheable so Anthropic stores them server-side between requests",
        "A CI/CD pipeline orchestrator for container deployments",
        "A client-side JavaScript library for DOM rendering"
      ],
      "correctIndex": 1,
      "explanation": "Prompt caching lets you mark parts of your prompt as cacheable so Anthropic stores them server-side between requests"
    },
    {
      "id": "ai-prompt-caching-fact-0",
      "question": "Which of these is true about Claude Prompt Caching (Key Mechanics)?",
      "choices": [
        "Use cache_control on the last cacheable block: only the content up to and including the marked block is cached.",
        "Cache write: 25% MORE than base input price (one-time cost to store)",
        "Batch similar requests: group requests that share the same prefix within the 5-min window.",
        "Put stable content first: system prompt → reference docs → examples → user message. Cache is prefix-based — anything after a change invalidates."
      ],
      "correctIndex": 1,
      "explanation": "Cache write: 25% MORE than base input price (one-time cost to store)"
    },
    {
      "id": "ai-prompt-caching-section",
      "question": "\"response = client.messages.create(\" — which section of Claude Prompt Caching does this belong to?",
      "choices": [
        "Best Practices",
        "Key Mechanics",
        "Token Pricing Breakdown",
        "When to Use It"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "ai-prompt-caching-bold-1",
      "question": "In the context of Claude Prompt Caching, which term matches: \"Cache write: 25% MORE than base input price (one-time cost to store)\"?",
      "choices": [
        "TTL",
        "Cache write",
        "Cache read",
        "90% cheaper"
      ],
      "correctIndex": 1,
      "explanation": "Cache write — from the \"Key Mechanics\" section."
    }
  ],
  "claude-x-obsidian-quant-mind-maps": [
    {
      "id": "claude-x-obsidian-quant-mind-maps-bold-0",
      "question": "In the context of Claude × Obsidian — Living Knowledge Graph, which term matches: \"Atomic notes: One concept per note. Link liberally.\"?",
      "choices": [
        "Output forces understanding",
        "Atomic notes",
        "Progressive summarization",
        "MOCs over folders"
      ],
      "correctIndex": 1,
      "explanation": "Atomic notes — from the \"Second Brain Best Practices (LYT Framework)\" section."
    },
    {
      "id": "claude-x-obsidian-quant-mind-maps-fact-0",
      "question": "Which of these is true about Claude × Obsidian — Living Knowledge Graph (Key Mechanics)?",
      "choices": [
        "Progressive summarization: Raw capture → highlight → bold → extract → your own words",
        "Claude generates atomic Pod notes and saves as `.md` with frontmatter",
        "Atomic notes: One concept per note. Link liberally.",
        "MOCs over folders: A note linking 20 related notes beats a folder of 20 files"
      ],
      "correctIndex": 1,
      "explanation": "Claude generates atomic Pod notes and saves as `.md` with frontmatter"
    },
    {
      "id": "claude-x-obsidian-quant-mind-maps-section",
      "question": "\"Claude generates atomic Pod notes and saves as `.md` with frontmatter\" — which section of Claude × Obsidian — Living Knowledge Graph does this belong to?",
      "choices": [
        "Implementation Guide",
        "Key Mechanics",
        "Second Brain Best Practices (LYT Framework)",
        "Obsidian Plugins Worth Adding"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "claude-x-obsidian-quant-mind-maps-bold-1",
      "question": "In the context of Claude × Obsidian — Living Knowledge Graph, which term matches: \"MOCs over folders: A note linking 20 related notes beats a folder of 20 files\"?",
      "choices": [
        "Atomic notes",
        "MOCs over folders",
        "Progressive summarization",
        "Output forces understanding"
      ],
      "correctIndex": 1,
      "explanation": "MOCs over folders — from the \"Second Brain Best Practices (LYT Framework)\" section."
    }
  ],
  "content-dashboard-claude-code-build": [
    {
      "id": "content-dashboard-claude-code-build-what",
      "question": "What best describes Content Dashboard — Claude Code Build Pattern (Shipyard)?",
      "choices": [
        "A hardware diagnostic tool for server maintenance",
        "A complete content operations platform built entirely with Claude Code in a single structured session",
        "A social media scheduling and analytics tool",
        "A customer relationship management (CRM) platform"
      ],
      "correctIndex": 1,
      "explanation": "A complete content operations platform built entirely with Claude Code in a single structured session"
    },
    {
      "id": "content-dashboard-claude-code-build-bold-0",
      "question": "In the context of Content Dashboard — Claude Code Build Pattern (Shipyard), which term matches: \"The CLAUDE.md step is the critical unlock — it gives Claude persistent context for all follow-up ses...\"?",
      "choices": [
        "A hardware diagnostic tool for server maintenance",
        "A social media scheduling and analytics tool",
        "CLAUDE.md step is the critical unlock",
        "A customer relationship management (CRM) platform"
      ],
      "correctIndex": 2,
      "explanation": "CLAUDE.md step is the critical unlock — from the \"The Master Scaffolding Prompt\" section."
    },
    {
      "id": "content-dashboard-claude-code-build-section",
      "question": "\"### Instagram Manager\" — which section of Content Dashboard — Claude Code Build Pattern (Shipyard) does this belong to?",
      "choices": [
        "The Master Scaffolding Prompt",
        "Implementation Guide",
        "The 5 App Sections (with their Claude prompts)",
        "Why It Matters"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"The 5 App Sections (with their Claude prompts)\" section."
    }
  ],
  "finance-accretion-dilution": [
    {
      "id": "finance-accretion-dilution-what",
      "question": "What best describes Accretion / Dilution Model?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "A social lending platform reputation score",
        "A technical charting pattern used in day trading",
        "Determines whether an acquisition increases (accretive) or decreases (dilutive) the acquirer's earnings per share (EPS)"
      ],
      "correctIndex": 3,
      "explanation": "Determines whether an acquisition increases (accretive) or decreases (dilutive) the acquirer's earnings per share (EPS)"
    },
    {
      "id": "finance-accretion-dilution-bold-0",
      "question": "In the context of Accretion / Dilution Model, which term matches: \"Accretive: Pro-forma EPS > Acquirer standalone EPS ✅\"?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "Accretive",
        "Dilutive",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "Accretive — from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-accretion-dilution-fact-0",
      "question": "Which of these is true about Accretion / Dilution Model (Key Mechanics)?",
      "choices": [
        "A social lending platform reputation score",
        "A cryptocurrency mining difficulty algorithm",
        "Accretive: Pro-forma EPS > Acquirer standalone EPS ✅",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 2,
      "explanation": "Accretive: Pro-forma EPS > Acquirer standalone EPS ✅"
    },
    {
      "id": "finance-accretion-dilution-section",
      "question": "\"Pro-forma EPS = (Acquirer NI + Target NI + Synergies − Cost of financing)\" — which section of Accretion / Dilution Model does this belong to?",
      "choices": [
        "Implementation Guide",
        "Key Mechanics",
        "Key Concept: Breakeven Synergies",
        "Why It Matters"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-accretion-dilution-bold-1",
      "question": "In the context of Accretion / Dilution Model, which term matches: \"Dilutive: Pro-forma EPS < Acquirer standalone EPS ⚠️\"?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "Dilutive",
        "Accretive",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "Dilutive — from the \"Key Mechanics\" section."
    }
  ],
  "finance-balance-sheet-analytics": [
    {
      "id": "finance-balance-sheet-analytics-what",
      "question": "What best describes Balance Sheet Analytics & ALM?",
      "choices": [
        "A social lending platform reputation score",
        "Asset-Liability Management (ALM) is how banks ensure they can meet obligations (deposits, withdrawals, loans) while maximizing profitability",
        "A cryptocurrency mining difficulty algorithm",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "Asset-Liability Management (ALM) is how banks ensure they can meet obligations (deposits, withdrawals, loans) while maximizing profitability"
    },
    {
      "id": "finance-balance-sheet-analytics-bold-0",
      "question": "In the context of Balance Sheet Analytics & ALM, which term matches: \"| Reporting cadence | Quarterly batch | Real-time, intraday |\"?",
      "choices": [
        "Liquidity gaps",
        "Reporting cadence",
        "Deposit visibility",
        "Risk identification"
      ],
      "correctIndex": 1,
      "explanation": "Reporting cadence — from the \"Legacy vs Modern\" section."
    },
    {
      "id": "finance-balance-sheet-analytics-section",
      "question": "\"What Banks Track (and how they currently do it):\" — which section of Balance Sheet Analytics & ALM does this belong to?",
      "choices": [
        "Why It Matters",
        "Key Mechanics",
        "Implementation Guide",
        "Legacy vs Modern"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-balance-sheet-analytics-bold-1",
      "question": "In the context of Balance Sheet Analytics & ALM, which term matches: \"| Deposit visibility | Aggregate totals | Per-account, per-flow |\"?",
      "choices": [
        "Reporting cadence",
        "Liquidity gaps",
        "Risk identification",
        "Deposit visibility"
      ],
      "correctIndex": 3,
      "explanation": "Deposit visibility — from the \"Legacy vs Modern\" section."
    }
  ],
  "finance-core-banking-integrations": [
    {
      "id": "finance-core-banking-integrations-what",
      "question": "What best describes Core Banking Integrations?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "Core banking systems are the central nervous system of every bank — they manage the ledger, process transactions, handle account records, and govern every dollar in and out",
        "A social lending platform reputation score",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "Core banking systems are the central nervous system of every bank — they manage the ledger, process transactions, handle account records, and govern every dollar in and out"
    },
    {
      "id": "finance-core-banking-integrations-section",
      "question": "\"The Big 3 Core Providers (collectively serve 70%+ of US banks):\" — which section of Core Banking Integrations does this belong to?",
      "choices": [
        "Why It Matters",
        "The Distribution Math",
        "Implementation Guide",
        "Key Mechanics"
      ],
      "correctIndex": 3,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "finance-cuso-structure": [
    {
      "id": "finance-cuso-structure-what",
      "question": "What best describes CUSO — Credit Union Service Organizations?",
      "choices": [
        "A technical charting pattern used in day trading",
        "A social lending platform reputation score",
        "A cryptocurrency mining difficulty algorithm",
        "A CUSO (Credit Union Service Organization) is a company owned by credit unions that provides services back to credit unions"
      ],
      "correctIndex": 3,
      "explanation": "A CUSO (Credit Union Service Organization) is a company owned by credit unions that provides services back to credit unions"
    },
    {
      "id": "finance-cuso-structure-fact-0",
      "question": "Which of these is true about CUSO — Credit Union Service Organizations (Key Mechanics)?",
      "choices": [
        "5,000+ credit unions in the US",
        "~$2T in total CU deposits — entirely untapped for deposit networks",
        "ModernFi has 75+ CUs onboarded (~1.5% penetration) in under 18 months",
        "Credit unions are nonprofit cooperatives (member-owned)"
      ],
      "correctIndex": 3,
      "explanation": "Credit unions are nonprofit cooperatives (member-owned)"
    },
    {
      "id": "finance-cuso-structure-section",
      "question": "\"Standard NCUA limit:     $250,000 per member, per credit union\" — which section of CUSO — Credit Union Service Organizations does this belong to?",
      "choices": [
        "Why It Matters",
        "Key Mechanics",
        "The Credit Union Opportunity",
        "Implementation Guide"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-cuso-structure-bold-1",
      "question": "In the context of CUSO — Credit Union Service Organizations, which term matches: \"5,000+ credit unions in the US\"?",
      "choices": [
        "first-ever deposit network for credit unions",
        "75+ CUs",
        "5,000+ credit unions",
        "~$2T in total CU deposits"
      ],
      "correctIndex": 2,
      "explanation": "5,000+ credit unions — from the \"The Credit Union Opportunity\" section."
    }
  ],
  "finance-dcf": [
    {
      "id": "finance-dcf-what",
      "question": "What best describes Discounted Cash Flow (DCF)?",
      "choices": [
        "A technical charting pattern used in day trading",
        "A cryptocurrency mining difficulty algorithm",
        "A social lending platform reputation score",
        "The foundational intrinsic valuation method"
      ],
      "correctIndex": 3,
      "explanation": "The foundational intrinsic valuation method"
    },
    {
      "id": "finance-dcf-bold-0",
      "question": "In the context of Discounted Cash Flow (DCF), which term matches: \"WACC: Weighted average cost of capital — tiny changes have huge impact\"?",
      "choices": [
        "A technical charting pattern used in day trading",
        "FCF margin trajectory",
        "WACC",
        "Terminal growth rate (g)"
      ],
      "correctIndex": 2,
      "explanation": "WACC — from the \"The Most Sensitive Inputs\" section."
    },
    {
      "id": "finance-dcf-fact-0",
      "question": "Which of these is true about Discounted Cash Flow (DCF) (The Most Sensitive Inputs)?",
      "choices": [
        "A technical charting pattern used in day trading",
        "WACC: Weighted average cost of capital — tiny changes have huge impact",
        "A cryptocurrency mining difficulty algorithm",
        "A social lending platform reputation score"
      ],
      "correctIndex": 1,
      "explanation": "WACC: Weighted average cost of capital — tiny changes have huge impact"
    },
    {
      "id": "finance-dcf-section",
      "question": "\"FCF = EBIT × (1 − tax rate) + D&A − CapEx − ΔWorking Capital\" — which section of Discounted Cash Flow (DCF) does this belong to?",
      "choices": [
        "Implementation Guide",
        "The Uncomfortable Truth",
        "Key Mechanics",
        "The Most Sensitive Inputs"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-dcf-bold-1",
      "question": "In the context of Discounted Cash Flow (DCF), which term matches: \"Terminal growth rate (g): Usually 2-3% (GDP growth). Most important assumption in the whole model.\"?",
      "choices": [
        "WACC",
        "Terminal growth rate (g)",
        "A technical charting pattern used in day trading",
        "FCF margin trajectory"
      ],
      "correctIndex": 1,
      "explanation": "Terminal growth rate (g) — from the \"The Most Sensitive Inputs\" section."
    }
  ],
  "finance-lbo-model": [
    {
      "id": "finance-lbo-model-what",
      "question": "What best describes Leveraged Buyout (LBO) Model?",
      "choices": [
        "A social lending platform reputation score",
        "A cryptocurrency mining difficulty algorithm",
        "Values a company by modeling an acquisition funded primarily with debt (~70-80%)",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 2,
      "explanation": "Values a company by modeling an acquisition funded primarily with debt (~70-80%)"
    },
    {
      "id": "finance-lbo-model-bold-0",
      "question": "In the context of Leveraged Buyout (LBO) Model, which term matches: \"1. Entry: Buy at X × EBITDA; fund with ~70% debt / ~30% equity\"?",
      "choices": [
        "Operations",
        "Entry",
        "Exit",
        "Debt paydown"
      ],
      "correctIndex": 1,
      "explanation": "Entry — from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-lbo-model-section",
      "question": "\"1. Entry: Buy at X × EBITDA; fund with ~70% debt / ~30% equity\" — which section of Leveraged Buyout (LBO) Model does this belong to?",
      "choices": [
        "Why It Matters",
        "Key Mechanics",
        "Key Formula",
        "Implementation Guide"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-lbo-model-bold-1",
      "question": "In the context of Leveraged Buyout (LBO) Model, which term matches: \"2. Operations: Project revenue, EBITDA, and free cash flow over hold period\"?",
      "choices": [
        "Entry",
        "Exit",
        "Debt paydown",
        "Operations"
      ],
      "correctIndex": 3,
      "explanation": "Operations — from the \"Key Mechanics\" section."
    }
  ],
  "finance-reciprocal-deposits": [
    {
      "id": "finance-reciprocal-deposits-what",
      "question": "What best describes Reciprocal Deposits?",
      "choices": [
        "A social lending platform reputation score",
        "The mechanism that extends FDIC/NCUA deposit insurance far beyond the standard $250K cap",
        "A cryptocurrency mining difficulty algorithm",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "The mechanism that extends FDIC/NCUA deposit insurance far beyond the standard $250K cap"
    },
    {
      "id": "finance-reciprocal-deposits-bold-0",
      "question": "In the context of Reciprocal Deposits, which term matches: \"The 2018 Economic Growth, Regulatory Relief, and Consumer Protection Act (Section 202) was the game-...\"?",
      "choices": [
        "non-brokered",
        "\"well capitalized\"",
        "CAMELS rating of 1 or 2",
        "Economic Growth, Regulatory Relief, and Consumer Protection Act"
      ],
      "correctIndex": 3,
      "explanation": "Economic Growth, Regulatory Relief, and Consumer Protection Act — from the \"Regulatory Classification\" section."
    },
    {
      "id": "finance-reciprocal-deposits-fact-0",
      "question": "Which of these is true about Reciprocal Deposits (Key Mechanics)?",
      "choices": [
        "Reciprocal deposits are now classified as non-brokered (up to the lesser of $5B or 20% of total liabilities)",
        "Only applies to banks that are \"well capitalized\" (CET1 >= 6.5%, Tier 1 >= 8%, Total RBC >= 10%, Leverage >= 5%)",
        "This matters enormously — brokered deposits carry higher regulatory costs, capital requirements, and restrictions",
        "Exchanges are reciprocal, so most flows cancel out (net settlement)"
      ],
      "correctIndex": 3,
      "explanation": "Exchanges are reciprocal, so most flows cancel out (net settlement)"
    },
    {
      "id": "finance-reciprocal-deposits-section",
      "question": "\"Standard FDIC limit:     $250,000 per depositor, per bank, per ownership category\" — which section of Reciprocal Deposits does this belong to?",
      "choices": [
        "The Market Today",
        "Key Mechanics",
        "Regulatory Classification",
        "Why It Matters"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-reciprocal-deposits-bold-1",
      "question": "In the context of Reciprocal Deposits, which term matches: \"Reciprocal deposits are now classified as non-brokered (up to the lesser of $5B or 20% of total liab...\"?",
      "choices": [
        "Economic Growth, Regulatory Relief, and Consumer Protection Act",
        "CAMELS rating of 1 or 2",
        "non-brokered",
        "\"well capitalized\""
      ],
      "correctIndex": 2,
      "explanation": "non-brokered — from the \"Regulatory Classification\" section."
    }
  ],
  "finance-relative-valuation": [
    {
      "id": "finance-relative-valuation-what",
      "question": "What best describes Relative Valuation (Trading Comps)?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "A technical charting pattern used in day trading",
        "Values a company by comparing it to publicly traded peers using market multiples — EV/EBITDA, P/E, P/S, EV/Revenue",
        "A social lending platform reputation score"
      ],
      "correctIndex": 2,
      "explanation": "Values a company by comparing it to publicly traded peers using market multiples — EV/EBITDA, P/E, P/S, EV/Revenue"
    },
    {
      "id": "finance-relative-valuation-section",
      "question": "\"1. Select a peer group of 5-10 comparable public companies\" — which section of Relative Valuation (Trading Comps) does this belong to?",
      "choices": [
        "Multiples by Sector",
        "Key Mechanics",
        "Why It Matters",
        "Implementation Guide"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "finance-wholesale-funding-market": [
    {
      "id": "finance-wholesale-funding-market-what",
      "question": "What best describes Wholesale Funding Market?",
      "choices": [
        "A technical charting pattern used in day trading",
        "The $2.3 trillion over-the-counter market where banks source large-scale funding beyond their retail deposit base",
        "A social lending platform reputation score",
        "A cryptocurrency mining difficulty algorithm"
      ],
      "correctIndex": 1,
      "explanation": "The $2.3 trillion over-the-counter market where banks source large-scale funding beyond their retail deposit base"
    },
    {
      "id": "finance-wholesale-funding-market-bold-0",
      "question": "In the context of Wholesale Funding Market, which term matches: \"Relationship-driven: Banks trust specific brokers built over decades\"?",
      "choices": [
        "Regulatory complexity",
        "Fragmented infrastructure",
        "Low transaction frequency",
        "Relationship-driven"
      ],
      "correctIndex": 3,
      "explanation": "Relationship-driven — from the \"Why It's Still Manual\" section."
    },
    {
      "id": "finance-wholesale-funding-market-fact-0",
      "question": "Which of these is true about Wholesale Funding Market (Why It's Still Manual)?",
      "choices": [
        "A cryptocurrency mining difficulty algorithm",
        "Relationship-driven: Banks trust specific brokers built over decades",
        "A social lending platform reputation score",
        "A technical charting pattern used in day trading"
      ],
      "correctIndex": 1,
      "explanation": "Relationship-driven: Banks trust specific brokers built over decades"
    },
    {
      "id": "finance-wholesale-funding-market-section",
      "question": "\"Wholesale Funding Sources (approximate breakdown):\" — which section of Wholesale Funding Market does this belong to?",
      "choices": [
        "Why It's Still Manual",
        "Key Mechanics",
        "Key Players",
        "The LCR Problem (Why Regulation Drives This Market)"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "finance-wholesale-funding-market-bold-1",
      "question": "In the context of Wholesale Funding Market, which term matches: \"Regulatory complexity: Each instrument type has different classification rules\"?",
      "choices": [
        "Low transaction frequency",
        "Regulatory complexity",
        "Relationship-driven",
        "Fragmented infrastructure"
      ],
      "correctIndex": 1,
      "explanation": "Regulatory complexity — from the \"Why It's Still Manual\" section."
    }
  ],
  "how-possible-is-this": [
    {
      "id": "how-possible-is-this-what",
      "question": "What best describes How Possible Is This?",
      "choices": [
        "A database management interface",
        "<!-- Captured from Slack: How possible is this? How realistic? -->\r\n<!-- Enrich this pod with /learn-capture or manually -->",
        "A network monitoring tool",
        "A hardware diagnostic utility"
      ],
      "correctIndex": 1,
      "explanation": "<!-- Captured from Slack: How possible is this? How realistic? -->\r\n<!-- Enrich this pod with /learn-capture or manually -->"
    }
  ],
  "ml-baseline-models": [
    {
      "id": "ml-baseline-models-what",
      "question": "What best describes ML - Baseline Models?",
      "choices": [
        "A relational database query optimizer",
        "A front-end CSS framework for responsive design",
        "A containerization platform for microservices",
        "Simple, naive strategies that any ML model must beat convincingly to prove it has real predictive power"
      ],
      "correctIndex": 3,
      "explanation": "Simple, naive strategies that any ML model must beat convincingly to prove it has real predictive power"
    },
    {
      "id": "ml-baseline-models-bold-0",
      "question": "In the context of ML - Baseline Models, which term matches: \"Simple, naive strategies that any ML model must beat convincingly to prove it has real predictive po...\"?",
      "choices": [
        "+4.5% edge",
        "beat convincingly",
        "after costs",
        "+0.6% edge"
      ],
      "correctIndex": 1,
      "explanation": "beat convincingly — from the \"What They Are\" section."
    },
    {
      "id": "ml-baseline-models-fact-0",
      "question": "Which of these is true about ML - Baseline Models (Why They Matter)?",
      "choices": [
        "BTC XGBoost: 52.3% vs 51.7% always_up = +0.6% edge (too thin)",
        "Altcoin XGBoost: 54.7% vs 50.2% random = +4.5% edge (promising but needs more trades)",
        "Crypto has a historical upward bias — \"always up\" often beats 50% accuracy",
        "\"Always up\" accuracy varies hugely by market regime (90%+ in bull, 30% in bear)"
      ],
      "correctIndex": 2,
      "explanation": "Crypto has a historical upward bias — \"always up\" often beats 50% accuracy"
    },
    {
      "id": "ml-baseline-models-section",
      "question": "\"Simple, naive strategies that any ML model must beat convincingly to prove it has real predictive power. If your complex...\" — which section of ML - Baseline Models does this belong to?",
      "choices": [
        "How to Interpret",
        "What They Are",
        "Signal Forge Baselines",
        "Why They Matter"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"What They Are\" section."
    },
    {
      "id": "ml-baseline-models-bold-1",
      "question": "In the context of ML - Baseline Models, which term matches: \"Your model must clear these bars after costs to have tradeable alpha\"?",
      "choices": [
        "+4.5% edge",
        "after costs",
        "+0.6% edge",
        "beat convincingly"
      ],
      "correctIndex": 1,
      "explanation": "after costs — from the \"Why They Matter\" section."
    }
  ],
  "ml-calibration-and-ece": [
    {
      "id": "ml-calibration-and-ece-what",
      "question": "What best describes ML - Calibration and ECE?",
      "choices": [
        "A relational database query optimizer",
        "A containerization platform for microservices",
        "A front-end CSS framework for responsive design",
        "Calibration measures whether a model's confidence scores are honest"
      ],
      "correctIndex": 3,
      "explanation": "Calibration measures whether a model's confidence scores are honest"
    },
    {
      "id": "ml-calibration-and-ece-fact-0",
      "question": "Which of these is true about ML - Calibration and ECE (Why It Matters for Trading)?",
      "choices": [
        "avg_accuracy   = actual win rate in that bin",
        "Quant - Kelly Criterion uses confidence to size positions: P(win) = confidence",
        "avg_confidence = mean predicted probability",
        "gap = |avg_confidence - avg_accuracy|"
      ],
      "correctIndex": 1,
      "explanation": "Quant - Kelly Criterion uses confidence to size positions: P(win) = confidence"
    },
    {
      "id": "ml-calibration-and-ece-section",
      "question": "\"Quant - Kelly Criterion uses confidence to size positions: P(win) = confidence\" — which section of ML - Calibration and ECE does this belong to?",
      "choices": [
        "Calibration Methods",
        "Why It Matters for Trading",
        "How ECE Works",
        "Signal Forge Implementation"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Why It Matters for Trading\" section."
    },
    {
      "id": "ml-calibration-and-ece-bold-1",
      "question": "In the context of ML - Calibration and ECE, which term matches: \"Signal Forge applies a 50% Kelly discount when ECE >= 0.10 (uncalibrated)\"?",
      "choices": [
        "honest",
        "Isotonic Regression",
        "Platt Scaling",
        "50% Kelly discount"
      ],
      "correctIndex": 3,
      "explanation": "50% Kelly discount — from the \"Why It Matters for Trading\" section."
    }
  ],
  "ml-feature-engineering-for-crypto": [
    {
      "id": "ml-feature-engineering-for-crypto-what",
      "question": "What best describes ML - Feature Engineering for Crypto?",
      "choices": [
        "A relational database query optimizer",
        "The process of transforming raw price/volume data into meaningful inputs for ML models",
        "A front-end CSS framework for responsive design",
        "A containerization platform for microservices"
      ],
      "correctIndex": 1,
      "explanation": "The process of transforming raw price/volume data into meaningful inputs for ML models"
    },
    {
      "id": "ml-feature-engineering-for-crypto-bold-0",
      "question": "In the context of ML - Feature Engineering for Crypto, which term matches: \"1. No Future Data\"?",
      "choices": [
        "4. Domain Knowledge > Brute Force",
        "1. No Future Data",
        "2. Stationarity",
        "3. Multiple Timescales"
      ],
      "correctIndex": 1,
      "explanation": "1. No Future Data — from the \"Feature Engineering Principles\" section."
    },
    {
      "id": "ml-feature-engineering-for-crypto-fact-0",
      "question": "Which of these is true about ML - Feature Engineering for Crypto (What's Missing (potential improvements))?",
      "choices": [
        "A relational database query optimizer",
        "A front-end CSS framework for responsive design",
        "A containerization platform for microservices",
        "Order flow / order book depth — who's buying vs selling"
      ],
      "correctIndex": 3,
      "explanation": "Order flow / order book depth — who's buying vs selling"
    },
    {
      "id": "ml-feature-engineering-for-crypto-section",
      "question": "\"### Returns (4 features)\" — which section of ML - Feature Engineering for Crypto does this belong to?",
      "choices": [
        "Implementation Guide",
        "What's Missing (potential improvements)",
        "Signal Forge's 27 Features (current)",
        "Feature Engineering Principles"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"Signal Forge's 27 Features (current)\" section."
    },
    {
      "id": "ml-feature-engineering-for-crypto-bold-1",
      "question": "In the context of ML - Feature Engineering for Crypto, which term matches: \"2. Stationarity\"?",
      "choices": [
        "4. Domain Knowledge > Brute Force",
        "2. Stationarity",
        "3. Multiple Timescales",
        "1. No Future Data"
      ],
      "correctIndex": 1,
      "explanation": "2. Stationarity — from the \"Feature Engineering Principles\" section."
    }
  ],
  "ml-walk-forward-validation": [
    {
      "id": "ml-walk-forward-validation-what",
      "question": "What best describes ML - Walk-Forward Validation?",
      "choices": [
        "A relational database query optimizer",
        "The only honest way to backtest a predictive model on time-series data",
        "A front-end CSS framework for responsive design",
        "A containerization platform for microservices"
      ],
      "correctIndex": 1,
      "explanation": "The only honest way to backtest a predictive model on time-series data"
    },
    {
      "id": "ml-walk-forward-validation-fact-0",
      "question": "Which of these is true about ML - Walk-Forward Validation (Key Concepts)?",
      "choices": [
        "Always compare against ML - Baseline Models — beating 50% means nothing if always_up gets 53%",
        "Expanding window: train set grows over time (uses all history). Better for regime detection.",
        "Retraining frequency matters: too often = overfitting to noise, too rarely = stale model",
        "Need enough data: train_window + step = minimum rows per fold (Signal Forge: 744 hours minimum)"
      ],
      "correctIndex": 1,
      "explanation": "Expanding window: train set grows over time (uses all history). Better for regime detection."
    },
    {
      "id": "ml-walk-forward-validation-section",
      "question": "\"Standard train/test splits (or k-fold cross-validation) leak future information in time-series data. A model trained on ...\" — which section of ML - Walk-Forward Validation does this belong to?",
      "choices": [
        "Key Concepts",
        "Why It Matters",
        "Signal Forge Implementation",
        "How It Works"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Why It Matters\" section."
    }
  ],
  "ml-xgboost-for-financial-prediction": [
    {
      "id": "ml-xgboost-for-financial-prediction-what",
      "question": "What best describes ML - XGBoost for Financial Prediction?",
      "choices": [
        "A relational database query optimizer",
        "A front-end CSS framework for responsive design",
        "A containerization platform for microservices",
        "Gradient-boosted decision tree ensemble"
      ],
      "correctIndex": 3,
      "explanation": "Gradient-boosted decision tree ensemble"
    },
    {
      "id": "ml-xgboost-for-financial-prediction-bold-0",
      "question": "In the context of ML - XGBoost for Financial Prediction, which term matches: \"Overfitting is the #1 risk — 95% train accuracy with 54% test accuracy = classic overfit\"?",
      "choices": [
        "A front-end CSS framework for responsive design",
        "Overfitting is the #1 risk",
        "A relational database query optimizer",
        "A containerization platform for microservices"
      ],
      "correctIndex": 1,
      "explanation": "Overfitting is the #1 risk — from the \"Gotchas in Finance\" section."
    },
    {
      "id": "ml-xgboost-for-financial-prediction-fact-0",
      "question": "Which of these is true about ML - XGBoost for Financial Prediction (How It Works)?",
      "choices": [
        "Trees memorize noise easily in financial data (low signal-to-noise ratio)",
        "Builds trees sequentially — each tree corrects the errors of the previous ones",
        "Overfitting is the #1 risk — 95% train accuracy with 54% test accuracy = classic overfit",
        "Feature importance can be misleading — correlated features split importance"
      ],
      "correctIndex": 1,
      "explanation": "Builds trees sequentially — each tree corrects the errors of the previous ones"
    },
    {
      "id": "ml-xgboost-for-financial-prediction-section",
      "question": "\"Builds trees sequentially — each tree corrects the errors of the previous ones\" — which section of ML - XGBoost for Financial Prediction does this belong to?",
      "choices": [
        "Key Parameters (Signal Forge defaults)",
        "How It Works",
        "Signal Forge Implementation",
        "Gotchas in Finance"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"How It Works\" section."
    }
  ],
  "openbb-terminal": [
    {
      "id": "openbb-terminal-what",
      "question": "What best describes OpenBB Terminal?",
      "choices": [
        "A hardware diagnostic tool for server maintenance",
        "Open-source Bloomberg alternative",
        "A social media scheduling and analytics tool",
        "A customer relationship management (CRM) platform"
      ],
      "correctIndex": 1,
      "explanation": "Open-source Bloomberg alternative"
    },
    {
      "id": "openbb-terminal-bold-0",
      "question": "In the context of OpenBB Terminal, which term matches: \"CLI mode: Run `openbb` in terminal for interactive exploration\"?",
      "choices": [
        "Data providers",
        "CLI mode",
        "A hardware diagnostic tool for server maintenance",
        "Python SDK"
      ],
      "correctIndex": 1,
      "explanation": "CLI mode — from the \"Key Mechanics\" section."
    },
    {
      "id": "openbb-terminal-fact-0",
      "question": "Which of these is true about OpenBB Terminal (Key Mechanics)?",
      "choices": [
        "A customer relationship management (CRM) platform",
        "CLI mode: Run `openbb` in terminal for interactive exploration",
        "A hardware diagnostic tool for server maintenance",
        "A social media scheduling and analytics tool"
      ],
      "correctIndex": 1,
      "explanation": "CLI mode: Run `openbb` in terminal for interactive exploration"
    },
    {
      "id": "openbb-terminal-section",
      "question": "\"CLI mode: Run `openbb` in terminal for interactive exploration\" — which section of OpenBB Terminal does this belong to?",
      "choices": [
        "Why It Matters",
        "Key Mechanics",
        "Python Entry Point",
        "Implementation Guide"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "openbb-terminal-bold-1",
      "question": "In the context of OpenBB Terminal, which term matches: \"Python SDK: `from openbb import obb` for programmatic access and automation\"?",
      "choices": [
        "CLI mode",
        "A hardware diagnostic tool for server maintenance",
        "Data providers",
        "Python SDK"
      ],
      "correctIndex": 3,
      "explanation": "Python SDK — from the \"Key Mechanics\" section."
    }
  ],
  "powerbi-claude-follower-dashboard": [
    {
      "id": "powerbi-claude-follower-dashboard-what",
      "question": "What best describes PowerBI + Claude — Intelligent Follower Dashboard?",
      "choices": [
        "A customer relationship management (CRM) platform",
        "A social media scheduling and analytics tool",
        "A hardware diagnostic tool for server maintenance",
        "Augmenting a standard PowerBI dashboard with Claude-generated narrative intelligence — natural language summaries, anomaly detection, and recommendations layered on top of standard charts"
      ],
      "correctIndex": 3,
      "explanation": "Augmenting a standard PowerBI dashboard with Claude-generated narrative intelligence — natural language summaries, anomaly detection, and recommendations layered on top of standard charts"
    },
    {
      "id": "powerbi-claude-follower-dashboard-section",
      "question": "\"1. PowerBI pulls social or operational data (Metricool, CSV export, native connectors)\" — which section of PowerBI + Claude — Intelligent Follower Dashboard does this belong to?",
      "choices": [
        "Claude Prompt Pattern",
        "Key Mechanics",
        "Why It Matters",
        "Implementation Guide"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "quant-circuit-breakers": [
    {
      "id": "quant-circuit-breakers-what",
      "question": "What best describes Quant - Circuit Breakers?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "Automated rules that reduce or halt trading when losses exceed predefined thresholds",
        "A social media sentiment aggregation score",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "Automated rules that reduce or halt trading when losses exceed predefined thresholds"
    },
    {
      "id": "quant-circuit-breakers-fact-0",
      "question": "Which of these is true about Quant - Circuit Breakers (Signal Forge Implementation)?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Cancel aggressive signals",
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Cancel aggressive signals"
    },
    {
      "id": "quant-circuit-breakers-section",
      "question": "\"Automated rules that reduce or halt trading when losses exceed predefined thresholds. Named after stock exchange circuit...\" — which section of Quant - Circuit Breakers does this belong to?",
      "choices": [
        "The Psychology",
        "What They Are",
        "Signal Forge Implementation",
        "Why They Exist"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"What They Are\" section."
    },
    {
      "id": "quant-circuit-breakers-bold-1",
      "question": "In the context of Quant - Circuit Breakers, which term matches: \"SOFT (-10% drawdown)\"?",
      "choices": [
        "reduce or halt trading",
        "KILL (-30% drawdown)",
        "SOFT (-10% drawdown)",
        "HARD (-20% drawdown)"
      ],
      "correctIndex": 2,
      "explanation": "SOFT (-10% drawdown) — from the \"Signal Forge Implementation\" section."
    }
  ],
  "quant-factor-and-correlation": [
    {
      "id": "quant-factor-and-correlation-what",
      "question": "What best describes Factor & Correlation Models?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Decomposes asset returns into exposure to systematic risk factors (value, momentum, quality, size) via regression",
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Decomposes asset returns into exposure to systematic risk factors (value, momentum, quality, size) via regression"
    },
    {
      "id": "quant-factor-and-correlation-fact-0",
      "question": "Which of these is true about Factor & Correlation Models (Key Mechanics)?",
      "choices": [
        "A social media sentiment aggregation score",
        "Estimate βs (factor loadings) via OLS regression",
        "A fixed interest rate instrument with no market risk",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "Estimate βs (factor loadings) via OLS regression"
    },
    {
      "id": "quant-factor-and-correlation-section",
      "question": "\"r_i = α + β₁·F₁ + β₂·F₂ + ... + ε\" — which section of Factor & Correlation Models does this belong to?",
      "choices": [
        "Python Entry Point",
        "Key Mechanics",
        "Implementation Guide",
        "Why It Matters"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "quant-kelly-criterion": [
    {
      "id": "quant-kelly-criterion-what",
      "question": "What best describes Quant - Kelly Criterion?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score",
        "A mathematical formula for the optimal bet size given your edge and odds",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 2,
      "explanation": "A mathematical formula for the optimal bet size given your edge and odds"
    },
    {
      "id": "quant-kelly-criterion-fact-0",
      "question": "Which of these is true about Quant - Kelly Criterion (Backtest Results)?",
      "choices": [
        "Kelly is growth-optimal but not utility-optimal — most humans can't stomach the variance",
        "With quarter-Kelly + costs: $10,000 -> ~$10,000 (capital preserved, 20-22 trades)",
        "Kelly assumes independent bets — correlated trades (all crypto at once) break the assumption",
        "Transaction costs eat directly into Kelly edge — must be modeled"
      ],
      "correctIndex": 1,
      "explanation": "With quarter-Kelly + costs: $10,000 -> ~$10,000 (capital preserved, 20-22 trades)"
    },
    {
      "id": "quant-kelly-criterion-section",
      "question": "\"Kelly % = W - (1 - W) / R\" — which section of Quant - Kelly Criterion does this belong to?",
      "choices": [
        "Why Fractional Kelly",
        "The Formula",
        "Connection to Calibration",
        "Signal Forge Implementation"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"The Formula\" section."
    },
    {
      "id": "quant-kelly-criterion-bold-1",
      "question": "In the context of Quant - Kelly Criterion, which term matches: \"Full Kelly maximizes long-term growth but produces huge drawdowns. In practice:\"?",
      "choices": [
        "optimal bet size",
        "1/4 Kelly",
        "50% of max",
        "huge drawdowns"
      ],
      "correctIndex": 3,
      "explanation": "huge drawdowns — from the \"Why Fractional Kelly\" section."
    }
  ],
  "quant-macro-regime-allocation": [
    {
      "id": "quant-macro-regime-allocation-what",
      "question": "What best describes Macro Regime Allocation Models?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "Classifies the current macroeconomic environment into a discrete regime (growth/recession × inflation/deflation), then allocates to asset classes that historically outperform in that regime",
        "A fundamental accounting metric used in GAAP reporting",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Classifies the current macroeconomic environment into a discrete regime (growth/recession × inflation/deflation), then allocates to asset classes that historically outperform in that regime"
    },
    {
      "id": "quant-macro-regime-allocation-bold-0",
      "question": "In the context of Macro Regime Allocation Models, which term matches: \"Regime detection: Hidden Markov Models (HMM) on returns, or K-Means clustering on macro indicators (...\"?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Regime detection",
        "Asset class winners per regime",
        "Classic 4 regimes"
      ],
      "correctIndex": 1,
      "explanation": "Regime detection — from the \"Key Mechanics\" section."
    },
    {
      "id": "quant-macro-regime-allocation-fact-0",
      "question": "Which of these is true about Macro Regime Allocation Models (Key Mechanics)?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score",
        "Regime detection: Hidden Markov Models (HMM) on returns, or K-Means clustering on macro indicators (PMI, CPI, yield curve slope)",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 2,
      "explanation": "Regime detection: Hidden Markov Models (HMM) on returns, or K-Means clustering on macro indicators (PMI, CPI, yield curve slope)"
    },
    {
      "id": "quant-macro-regime-allocation-section",
      "question": "\"Regime detection: Hidden Markov Models (HMM) on returns, or K-Means clustering on macro indicators (PMI, CPI, yield curv...\" — which section of Macro Regime Allocation Models does this belong to?",
      "choices": [
        "Implementation Guide",
        "Key Mechanics",
        "Why It Matters",
        "Python Entry Point"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "quant-macro-regime-allocation-bold-1",
      "question": "In the context of Macro Regime Allocation Models, which term matches: \"Classic 4 regimes: Goldilocks (↑growth ↓inflation), Reflation (↑growth ↑inflation), Stagflation (↓gr...\"?",
      "choices": [
        "Regime detection",
        "Classic 4 regimes",
        "Asset class winners per regime",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "Classic 4 regimes — from the \"Key Mechanics\" section."
    }
  ],
  "quant-maximum-drawdown": [
    {
      "id": "quant-maximum-drawdown-what",
      "question": "What best describes Quant - Maximum Drawdown?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "The largest peak-to-trough decline in portfolio value before a new high is reached",
        "A social media sentiment aggregation score",
        "A fixed interest rate instrument with no market risk"
      ],
      "correctIndex": 1,
      "explanation": "The largest peak-to-trough decline in portfolio value before a new high is reached"
    },
    {
      "id": "quant-maximum-drawdown-bold-0",
      "question": "In the context of Quant - Maximum Drawdown, which term matches: \"The largest peak-to-trough decline in portfolio value before a new high is reached. Measures the wor...\"?",
      "choices": [
        "> 0.5",
        "peak-to-trough decline",
        "< 25%",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "peak-to-trough decline — from the \"What It Is\" section."
    },
    {
      "id": "quant-maximum-drawdown-section",
      "question": "\"At any point in time:\" — which section of Quant - Maximum Drawdown does this belong to?",
      "choices": [
        "Why It Matters More Than Returns",
        "Circuit Breaker Integration",
        "How to Calculate",
        "Signal Forge Results"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"How to Calculate\" section."
    },
    {
      "id": "quant-maximum-drawdown-bold-1",
      "question": "In the context of Quant - Maximum Drawdown, which term matches: \"| Signal Forge target | < 25% | > 0.5 |\"?",
      "choices": [
        "> 0.5",
        "< 25%",
        "peak-to-trough decline",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "< 25% — from the \"Professional Benchmarks\" section."
    }
  ],
  "quant-relative-value-spread": [
    {
      "id": "quant-relative-value-spread-what",
      "question": "What best describes Relative Value / Spread Models?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score",
        "Identifies mispriced relationships between related assets (pairs or baskets)",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 2,
      "explanation": "Identifies mispriced relationships between related assets (pairs or baskets)"
    },
    {
      "id": "quant-relative-value-spread-section",
      "question": "\"1. Test for cointegration: `engle_granger(price_A, price_B)`\" — which section of Relative Value / Spread Models does this belong to?",
      "choices": [
        "Implementation Guide",
        "Why It Matters",
        "Key Mechanics",
        "Python Entry Point"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "quant-sharpe-ratio": [
    {
      "id": "quant-sharpe-ratio-what",
      "question": "What best describes Quant - Sharpe Ratio?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "A social media sentiment aggregation score",
        "The risk-adjusted return of a strategy",
        "A fixed interest rate instrument with no market risk"
      ],
      "correctIndex": 2,
      "explanation": "The risk-adjusted return of a strategy"
    },
    {
      "id": "quant-sharpe-ratio-bold-0",
      "question": "In the context of Quant - Sharpe Ratio, which term matches: \"The risk-adjusted return of a strategy. Measures how much return you get per unit of risk (volatilit...\"?",
      "choices": [
        "Signal Forge BTC: 1.02",
        "Tradeable",
        "risk-adjusted return",
        "0.5 - 1.0"
      ],
      "correctIndex": 2,
      "explanation": "risk-adjusted return — from the \"What It Is\" section."
    },
    {
      "id": "quant-sharpe-ratio-fact-0",
      "question": "Which of these is true about Quant - Sharpe Ratio (Why It Matters)?",
      "choices": [
        "Penalizes upside volatility same as downside (Sortino Ratio fixes this)",
        "Strategy A: +50% return, 80% volatility -> Sharpe = 0.63",
        "Sensitive to the time period chosen",
        "Assumes returns are normally distributed (crypto returns are fat-tailed — they're not)"
      ],
      "correctIndex": 1,
      "explanation": "Strategy A: +50% return, 80% volatility -> Sharpe = 0.63"
    },
    {
      "id": "quant-sharpe-ratio-section",
      "question": "\"Sharpe = (Mean Return - Risk-Free Rate) / Std Dev of Returns\" — which section of Quant - Sharpe Ratio does this belong to?",
      "choices": [
        "Signal Forge Results",
        "Why It Matters",
        "The Formula",
        "How to Read It"
      ],
      "correctIndex": 2,
      "explanation": "This is from the \"The Formula\" section."
    },
    {
      "id": "quant-sharpe-ratio-bold-1",
      "question": "In the context of Quant - Sharpe Ratio, which term matches: \"| 0.5 - 1.0 | Tradeable | Signal Forge BTC: 1.02 |\"?",
      "choices": [
        "Tradeable",
        "0.5 - 1.0",
        "risk-adjusted return",
        "Signal Forge BTC: 1.02"
      ],
      "correctIndex": 1,
      "explanation": "0.5 - 1.0 — from the \"How to Read It\" section."
    }
  ],
  "quant-time-series-momentum": [
    {
      "id": "quant-time-series-momentum-what",
      "question": "What best describes Time-Series Momentum Models?",
      "choices": [
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score",
        "A strategy that goes long assets that have risen over a lookback window (e.g",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 2,
      "explanation": "A strategy that goes long assets that have risen over a lookback window (e.g"
    },
    {
      "id": "quant-time-series-momentum-bold-0",
      "question": "In the context of Time-Series Momentum Models, which term matches: \"Signal = sign of past return over N-month window\"?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Signal",
        "Position size",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Signal — from the \"Key Mechanics\" section."
    },
    {
      "id": "quant-time-series-momentum-fact-0",
      "question": "Which of these is true about Time-Series Momentum Models (Key Mechanics)?",
      "choices": [
        "A social media sentiment aggregation score",
        "Signal = sign of past return over N-month window",
        "A fixed interest rate instrument with no market risk",
        "A fundamental accounting metric used in GAAP reporting"
      ],
      "correctIndex": 1,
      "explanation": "Signal = sign of past return over N-month window"
    },
    {
      "id": "quant-time-series-momentum-section",
      "question": "\"Signal = sign of past return over N-month window\" — which section of Time-Series Momentum Models does this belong to?",
      "choices": [
        "Why It Matters",
        "Key Mechanics",
        "Implementation Guide",
        "Python Entry Point"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    },
    {
      "id": "quant-time-series-momentum-bold-1",
      "question": "In the context of Time-Series Momentum Models, which term matches: \"Position size ∝ signal strength / realized volatility\"?",
      "choices": [
        "Signal",
        "Position size",
        "A fundamental accounting metric used in GAAP reporting",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Position size — from the \"Key Mechanics\" section."
    }
  ],
  "quant-transaction-costs": [
    {
      "id": "quant-transaction-costs-what",
      "question": "What best describes Quant - Transaction Costs?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score",
        "The real-world costs of executing trades that backtest results often ignore"
      ],
      "correctIndex": 3,
      "explanation": "The real-world costs of executing trades that backtest results often ignore"
    },
    {
      "id": "quant-transaction-costs-bold-0",
      "question": "In the context of Quant - Transaction Costs, which term matches: \"| Signal Forge (daily signals) | ~300 | Mitigated by Kelly sizing only trading high-confidence |\"?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Signal Forge (daily signals)",
        "Mitigated by Kelly sizing only trading high-confidence",
        "~300"
      ],
      "correctIndex": 1,
      "explanation": "Signal Forge (daily signals) — from the \"The Frequency Trap\" section."
    },
    {
      "id": "quant-transaction-costs-fact-0",
      "question": "Which of these is true about Quant - Transaction Costs (The Three Costs)?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Order book depth (your order moves the price)",
        "A fixed interest rate instrument with no market risk",
        "A social media sentiment aggregation score"
      ],
      "correctIndex": 1,
      "explanation": "Order book depth (your order moves the price)"
    },
    {
      "id": "quant-transaction-costs-section",
      "question": "\"The real-world costs of executing trades that backtest results often ignore. The silent killer of strategies that look p...\" — which section of Quant - Transaction Costs does this belong to?",
      "choices": [
        "Impact on Signal Forge",
        "What They Are",
        "Total Cost Per Trade",
        "The Three Costs"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"What They Are\" section."
    },
    {
      "id": "quant-transaction-costs-bold-1",
      "question": "In the context of Quant - Transaction Costs, which term matches: \"| Signal Forge (daily signals) | ~300 | Mitigated by Kelly sizing only trading high-confidence |\"?",
      "choices": [
        "Signal Forge (daily signals)",
        "~300",
        "A fundamental accounting metric used in GAAP reporting",
        "Mitigated by Kelly sizing only trading high-confidence"
      ],
      "correctIndex": 1,
      "explanation": "~300 — from the \"The Frequency Trap\" section."
    }
  ],
  "quant-volatility-targeting": [
    {
      "id": "quant-volatility-targeting-what",
      "question": "What best describes Volatility Targeting Models?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "A social media sentiment aggregation score",
        "Dynamically scales position size so your portfolio maintains a constant target volatility (e.g",
        "A fixed interest rate instrument with no market risk"
      ],
      "correctIndex": 2,
      "explanation": "Dynamically scales position size so your portfolio maintains a constant target volatility (e.g"
    },
    {
      "id": "quant-volatility-targeting-fact-0",
      "question": "Which of these is true about Volatility Targeting Models (Key Mechanics)?",
      "choices": [
        "A fundamental accounting metric used in GAAP reporting",
        "Realized vol estimated via rolling std or EWMA (exponentially weighted moving average)",
        "A social media sentiment aggregation score",
        "A fixed interest rate instrument with no market risk"
      ],
      "correctIndex": 1,
      "explanation": "Realized vol estimated via rolling std or EWMA (exponentially weighted moving average)"
    },
    {
      "id": "quant-volatility-targeting-section",
      "question": "\"position_size = target_vol / realized_vol\" — which section of Volatility Targeting Models does this belong to?",
      "choices": [
        "Python Entry Point",
        "Key Mechanics",
        "Implementation Guide",
        "Why It Matters"
      ],
      "correctIndex": 1,
      "explanation": "This is from the \"Key Mechanics\" section."
    }
  ],
  "se-to-ai-engineer-6-month-roadmap": [
    {
      "id": "se-to-ai-engineer-6-month-roadmap-what",
      "question": "What best describes SE → AI Engineer: 6-Month Roadmap?",
      "choices": [
        "A database migration tool for PostgreSQL schemas",
        "A structured 6-month curriculum for a software engineer transitioning to AI/ML Engineering",
        "A client-side JavaScript library for DOM rendering",
        "A CI/CD pipeline orchestrator for container deployments"
      ],
      "correctIndex": 1,
      "explanation": "A structured 6-month curriculum for a software engineer transitioning to AI/ML Engineering"
    },
    {
      "id": "se-to-ai-engineer-6-month-roadmap-bold-0",
      "question": "In the context of SE → AI Engineer: 6-Month Roadmap, which term matches: \"7. Project: End-to-end dataset → model → evaluation pipeline\"?",
      "choices": [
        "A client-side JavaScript library for DOM rendering",
        "A database migration tool for PostgreSQL schemas",
        "A CI/CD pipeline orchestrator for container deployments",
        "Project"
      ],
      "correctIndex": 3,
      "explanation": "Project — from the \"Month 1 — Python, Data Handling & ML Foundations\" section."
    },
    {
      "id": "se-to-ai-engineer-6-month-roadmap-section",
      "question": "\"1. Advanced Python for ML: list/dict comprehensions, generators, decorators, typing\" — which section of SE → AI Engineer: 6-Month Roadmap does this belong to?",
      "choices": [
        "Month 2 — Machine Learning Deep Dive",
        "Month 4 — MLOps & Production Systems",
        "Month 3 — Deep Learning & Neural Networks",
        "Month 1 — Python, Data Handling & ML Foundations"
      ],
      "correctIndex": 3,
      "explanation": "This is from the \"Month 1 — Python, Data Handling & ML Foundations\" section."
    },
    {
      "id": "se-to-ai-engineer-6-month-roadmap-bold-1",
      "question": "In the context of SE → AI Engineer: 6-Month Roadmap, which term matches: \"7. Project: Production-style ML pipeline with proper validation and metrics\"?",
      "choices": [
        "A database migration tool for PostgreSQL schemas",
        "Project",
        "A CI/CD pipeline orchestrator for container deployments",
        "A client-side JavaScript library for DOM rendering"
      ],
      "correctIndex": 1,
      "explanation": "Project — from the \"Month 2 — Machine Learning Deep Dive\" section."
    }
  ]
};
